### ISSUE TITLE
how to deploy chart v2?

### ISSUE THREAD

**Issue by istok20** [reactjs/react-chartjs#138] opened 2016-07-29 18:45 UTC
I've installed v1, then install v2 running this:
 npm i react-chartjs@git://github.com/reactjs/react-chartjs.git#chartjs-v2

now, no charts are rendered at all..

when the route with chart (that is not visible) is changed, i get 

> core.js:46 Uncaught TypeError: chart.destroy is not a function

how to deploy chart v2 correctly?

**Comment by lindskogen** [comment] 2016-07-31 11:37
Are you using chartjs 2.0?

**Comment by istok20** [comment] 2016-08-01 12:55
no, just went back to v1, found out how to fill colors of datasets and that's ok for me:)

**Comment by pazs** [comment] 2016-08-02 15:26
hoW?

**Comment by cibelius** [comment] 2016-08-09 13:33
Is it possible to use chartjs 2.0 with react-chartjs?

**Comment by stavarengo** [comment] 2016-08-11 23:05
is it guys?

**Comment by ledsun** [comment] 2016-08-12 02:10
If you want to use chart.js v2, use `chartjs-v2` branch of the react-chart-js: 

```
npm i react-chartjs@git://github.com/reactjs/react-chartjs.git#chartjs-v2
```

If you want to use chart.js v1, read documents of chart.js v1:
https://github.com/chartjs/Chart.js/tree/v1.1.1/docs
Options of chart.js is changed.

**Comment by bactisme** [comment] 2016-08-22 12:41
When the V2 branch will be ready ?

**Comment by nrempel** [comment] 2016-08-29 21:23
Hey, for everyone looking to use chartjs 2: https://github.com/gor181/react-chartjs-2 is actively maintained and works with version 2. I've switched over. It works well and should be mostly compatible (just change import statement)

**Comment by couzic** [comment] 2016-10-04 08:27
Same here, I switched to [react-chartjs-2](https://github.com/gor181/react-chartjs-2) and so far I am happy. Same API and the repo is very active.

**Comment by benmccann** [comment] 2018-01-02 16:46
Duplicate of https://github.com/reactjs/react-chartjs/issues/84

**Comment by benmccann** [comment] 2018-01-03 07:07
I've closed this since it's a duplicate issue. I've also started discussion with the maintainers of react-chartjs-2 about merging that code into this repo

**Closed as completed** 2018-01-03 07:06 UTC
